SHOW TABLES;
SELECT 'USERS' as tbl, COUNT(*) as cnt FROM users
UNION ALL
SELECT 'REQUESTS', COUNT(*) FROM requests
UNION ALL
SELECT 'CHAT_SESSIONS', COUNT(*) FROM chat_sessions
UNION ALL
SELECT 'CHAT_MESSAGES', COUNT(*) FROM chat_messages
UNION ALL
SELECT 'KNOWLEDGE_BASE', COUNT(*) FROM knowledge_base
UNION ALL
SELECT 'PROMOS', COUNT(*) FROM promos
UNION ALL
SELECT 'ANALYTICS', COUNT(*) FROM analytics;
